// Preview data only. HTTP mode loads real activities from the authenticated API.
export function createPreviewActivities(now = new Date()) {
  const startsAt = (days, hour) => { const date = new Date(now); date.setDate(date.getDate() + days); date.setHours(hour,0,0,0); return date.toISOString(); };
  const attendees = (hostId, count) => [hostId, ...Array.from({length:count-1},(_,index) => `${hostId}_guest_${index}`)];
  return [
    {id:'high-park-run',title:'High Park morning run',sportId:'running',startsAt:startsAt(1,8),location:'High Park · Bloor Street entrance',distanceKm:5,pace:'Easy 5K · conversational',description:'Come on your own and meet others who enjoy an easy run. We’ll make introductions before a relaxed loop through High Park, with pauses to regroup and chat. Meet at the Bloor Street entrance ten minutes early. Bring water and running shoes; stay for coffee afterwards if you feel like it.',capacity:20,attendeeIds:attendees('host_alex',12),host:{id:'host_alex',name:'Alex',verified:true}},
    {id:'waterfront-ride',title:'Lakeside, at your pace',sportId:'cycling',startsAt:startsAt(2,9),location:'Sunnyside Pavilion · bike racks',distanceKm:18,pace:'Social ride · 18 km',description:'Meet a few new faces over a relaxed waterfront ride. We’ll introduce ourselves at the bike racks, regroup at the turns and stop for a chat along the way. Come with a bike, helmet and water; we finish back at Sunnyside.',capacity:12,attendeeIds:attendees('host_jordan',7),host:{id:'host_jordan',name:'Jordan',verified:true}},
    {id:'doubles-social',title:'A little doubles, a lot of fun',sportId:'tennis',startsAt:startsAt(3,18),location:'Trinity Bellwoods · tennis courts',pace:'Casual doubles · all levels',description:'Friendly doubles with rotating partners and time to get to know each other between games. Coming on your own is welcome. Meet outside the courts; we’ll share court time based on availability. Bring your racket. Tennis balls provided.',capacity:8,attendeeIds:attendees('host_sam',4),host:{id:'host_sam',name:'Sam',verified:false}},
    {id:'ravine-walk',title:'A reset in the ravine',sportId:'hiking',startsAt:startsAt(5,10),location:'Evergreen Brick Works · main entrance',distanceKm:4,pace:'Easy trails · 4 km',description:'Meet someone new on an unhurried walk through the Don Valley trails. We’ll say hello at the main entrance and head out together, with time to talk along the way. Come on your own, wear comfortable shoes, and bring water and a layer for the weather.',capacity:16,attendeeIds:attendees('host_robin',6),host:{id:'host_robin',name:'Robin',verified:true}},
  ];
}
