export const translations = {
  "zh-CN": {
    discoverEyebrow: "发现 · Toronto", discoverTitle: "遇见同频的人", likes: (count) => `${count} 次 Like`, distance: "距离", allSports: "全部运动", filterPreferences: "筛选偏好 →", selfieVerified: "✓ 自拍已认证", stravaConnected: "STRAVA 已连接", garminConnected: "GARMIN 已连接", mayaActivity: "跑步 · 骑行 · 3–4 次 / 周", mayaBio: "“慢跑 10K，聊聊天，再喝杯咖啡。一起吗？”", halfMarathon: "半马训练", advanced: "中高阶", networkGrowing: "还没遇见合适的人", cityOpening: "换个范围，继续认识", waitlistText: "附近暂时没有符合这些条件的人。试试其他运动，或扩大距离，给相识多一点可能。", joinWaitlist: "加入等待名单", connect: "连接", connectionTitle: "已有默契", bothVerified: "✓ 双方已认证", training10k: "从共同的 10K 目标开始聊起", chat: "聊天", realLikes: "真实喜欢", whoLikes: "谁喜欢了你", likesDescription: "看看谁已经对你心动。Plus 可查看完整资料。", viewPlus: "查看权益", train: "相约", trainTitle: "一起运动，慢慢认识", verifiedHost: "✓ 认证组织者", highParkRun: "High Park 晨跑", highParkDetails: "8:00 · 轻松 5K · 12 / 20 人", createEvent: "创建公开活动", plusHostTools: "Plus 组织工具", myProfile: "我的资料", kevinSports: "跑步 · 网球 · 骑行", kevinActivity: "4 次 / 周 · 中高阶", editProfile: "编辑资料", settingsAccount: "设置与账户", discoverTab: "发现", meTab: "我", settings: "设置", accountPreferences: "账户与偏好", billing: "账单与订阅", privacy: "隐私与运动数据", deleteAccount: "注销账户", logout: "退出登录", language: "语言", languageTitle: "显示语言", languageCaption: "选择 PACE 的界面语言", close: "关闭", plusTitle: "让相识更进一步", plusDescription: "用 Plus 查看谁喜欢你、在匹配前发出邀约，或组织公开活动认识更多人。", manageCancel: "$14.99 / 月 · 可随时在「设置与账户」中管理或取消", priceMonthly: "$14.99 / 月", subscribePlus: "订阅 Plus", filterApplied: "距离与项目偏好已应用。",
  },
  en: {
    discoverEyebrow: "Discover · Toronto", discoverTitle: "Meet someone on your wavelength", likes: (count) => `${count} Likes`, distance: "Distance", allSports: "All sports", filterPreferences: "Filter preferences →", selfieVerified: "✓ Selfie verified", stravaConnected: "STRAVA CONNECTED", garminConnected: "GARMIN CONNECTED", mayaActivity: "Running · Cycling · 3–4× / week", mayaBio: "“A slow 10K, good conversation, then coffee. Who’s in?”", halfMarathon: "Half-marathon", advanced: "Advanced", networkGrowing: "Still looking for your kind of person", cityOpening: "Make room for someone new", waitlistText: "No one nearby matches these filters yet. Try another sport or widen your distance to meet more people.", joinWaitlist: "Join waitlist", connect: "Connect", connectionTitle: "Shared momentum", bothVerified: "✓ Both verified", training10k: "A shared 10K goal. A place to start.", chat: "Chat", realLikes: "Real likes", whoLikes: "Who likes you", likesDescription: "Someone’s already interested. See their full profile with Plus.", viewPlus: "View Plus", train: "Meet up", trainTitle: "Meet through what you love", verifiedHost: "✓ Verified host", highParkRun: "High Park morning run", highParkDetails: "8:00 · Easy 5K · 12 / 20 people", createEvent: "Create public activity", plusHostTools: "Plus host tools", myProfile: "My profile", kevinSports: "Running · Tennis · Cycling", kevinActivity: "4× / week · Advanced", editProfile: "Edit profile", settingsAccount: "Settings & account", discoverTab: "Discover", meTab: "Me", settings: "Settings", accountPreferences: "Account & preferences", billing: "Billing & subscription", privacy: "Privacy & sport data", deleteAccount: "Delete account", logout: "Log out", language: "Language", languageTitle: "Display language", languageCaption: "Choose PACE's interface language", close: "Close", plusTitle: "Make the first move", plusDescription: "See who likes you, send an invite before matching, and host activities to meet new people with Plus.", manageCancel: "$14.99 / month · Manage or cancel any time in Settings & account", priceMonthly: "$14.99 / month", subscribePlus: "Subscribe to Plus", filterApplied: "Distance and sport preferences applied.",
  },
  fr: {
    discoverEyebrow: "Découvrir · Toronto", discoverTitle: "Rencontrez quelqu’un à votre rythme", likes: (count) => `${count} J’aime`, distance: "Distance", allSports: "Tous les sports", filterPreferences: "Préférences →", selfieVerified: "✓ Selfie vérifié", stravaConnected: "STRAVA CONNECTÉ", garminConnected: "GARMIN CONNECTÉ", mayaActivity: "Course · Vélo · 3–4× / semaine", mayaBio: "« Un 10 km tranquille, une bonne discussion, puis un café. Qui vient ? »", halfMarathon: "Semi-marathon", advanced: "Avancé", networkGrowing: "La bonne rencontre se fait attendre", cityOpening: "Ouvrez-vous à de nouvelles rencontres", waitlistText: "Personne à proximité ne correspond encore à ces filtres. Essayez un autre sport ou élargissez la distance.", joinWaitlist: "Rejoindre la liste", connect: "Connexions", connectionTitle: "Même élan", bothVerified: "✓ Tous deux vérifiés", training10k: "Un objectif de 10 km pour lancer la conversation.", chat: "Discuter", realLikes: "J’aime réels", whoLikes: "Qui vous aime", likesDescription: "Vous avez déjà attiré son attention. Découvrez son profil complet avec Plus.", viewPlus: "Voir Plus", train: "Sorties", trainTitle: "Rencontrez-vous autour de vos passions", verifiedHost: "✓ Organisateur vérifié", highParkRun: "Course matinale High Park", highParkDetails: "8 h · 5 km facile · 12 / 20 personnes", createEvent: "Créer une activité", plusHostTools: "Outils hôte Plus", myProfile: "Mon profil", kevinSports: "Course · Tennis · Vélo", kevinActivity: "4× / semaine · Avancé", editProfile: "Modifier le profil", settingsAccount: "Réglages et compte", discoverTab: "Découvrir", meTab: "Moi", settings: "Réglages", accountPreferences: "Compte et préférences", billing: "Facturation et abonnement", privacy: "Confidentialité et sport", deleteAccount: "Supprimer le compte", logout: "Se déconnecter", language: "Langue", languageTitle: "Langue d’affichage", languageCaption: "Choisissez la langue de PACE", close: "Fermer", plusTitle: "Faites le premier pas", plusDescription: "Avec Plus, découvrez qui vous aime, proposez une sortie avant le match et organisez des activités pour faire connaissance.", manageCancel: "14,99 $ / mois · Gérez ou annulez dans Réglages et compte", priceMonthly: "14,99 $ / mois", subscribePlus: "S’abonner à Plus", filterApplied: "Préférences de distance et de sport appliquées.",
  },
  es: {
    discoverEyebrow: "Descubrir · Toronto", discoverTitle: "Conoce a alguien a tu ritmo", likes: (count) => `${count} Me gusta`, distance: "Distancia", allSports: "Todos los deportes", filterPreferences: "Preferencias →", selfieVerified: "✓ Selfie verificado", stravaConnected: "STRAVA CONECTADO", garminConnected: "GARMIN CONECTADO", mayaActivity: "Running · Ciclismo · 3–4× / semana", mayaBio: "«10K tranquilos, buena conversación y después un café. ¿Te apuntas?»", halfMarathon: "Media maratón", advanced: "Avanzado", networkGrowing: "Esa conexión aún está por llegar", cityOpening: "Haz sitio para alguien nuevo", waitlistText: "Todavía nadie cerca coincide con estos filtros. Prueba otro deporte o amplía la distancia para conocer más personas.", joinWaitlist: "Unirme a la lista", connect: "Conexiones", connectionTitle: "Mismo impulso", bothVerified: "✓ Ambos verificados", training10k: "Un objetivo de 10K para romper el hielo.", chat: "Chat", realLikes: "Me gusta reales", whoLikes: "A quién le gustas", likesDescription: "Ya has despertado interés. Mira su perfil completo con Plus.", viewPlus: "Ver Plus", train: "Planes", trainTitle: "Conózcanse haciendo lo que les gusta", verifiedHost: "✓ Anfitrión verificado", highParkRun: "Running matutino en High Park", highParkDetails: "8:00 · 5K suave · 12 / 20 personas", createEvent: "Crear actividad pública", plusHostTools: "Herramientas Plus", myProfile: "Mi perfil", kevinSports: "Running · Tenis · Ciclismo", kevinActivity: "4× / semana · Avanzado", editProfile: "Editar perfil", settingsAccount: "Ajustes y cuenta", discoverTab: "Descubrir", meTab: "Yo", settings: "Ajustes", accountPreferences: "Cuenta y preferencias", billing: "Pagos y suscripción", privacy: "Privacidad y datos", deleteAccount: "Eliminar cuenta", logout: "Cerrar sesión", language: "Idioma", languageTitle: "Idioma de la interfaz", languageCaption: "Elige el idioma de PACE", close: "Cerrar", plusTitle: "Da el primer paso", plusDescription: "Con Plus, descubre a quién le gustas, invita antes de hacer match y organiza actividades para conocer gente.", manageCancel: "$14.99 / mes · Gestiona o cancela desde Ajustes y cuenta", priceMonthly: "$14.99 / mes", subscribePlus: "Suscribirme a Plus", filterApplied: "Se aplicaron tus preferencias de distancia y deporte.",
  },
  de: {
    discoverEyebrow: "Entdecken · Toronto", discoverTitle: "Triff jemanden auf deiner Wellenlänge", likes: (count) => `${count} Likes`, distance: "Distanz", allSports: "Alle Sportarten", filterPreferences: "Filtereinstellungen →", selfieVerified: "✓ Selfie verifiziert", stravaConnected: "STRAVA VERBUNDEN", garminConnected: "GARMIN VERBUNDEN", mayaActivity: "Laufen · Radfahren · 3–4× / Woche", mayaBio: "„Entspannte 10 km, gute Gespräche und danach ein Kaffee. Wer kommt mit?“", halfMarathon: "Halbmarathon", advanced: "Fortgeschritten", networkGrowing: "Dein nächstes Kennenlernen wartet noch", cityOpening: "Mach Platz für neue Begegnungen", waitlistText: "Noch passt niemand in deiner Nähe zu diesen Filtern. Probiere eine andere Sportart oder einen größeren Umkreis.", joinWaitlist: "Warteliste beitreten", connect: "Verbindungen", connectionTitle: "Gemeinsamer Antrieb", bothVerified: "✓ Beide verifiziert", training10k: "Ein gemeinsames 10-km-Ziel als Gesprächseinstieg.", chat: "Chat", realLikes: "Echte Likes", whoLikes: "Wer dich mag", likesDescription: "Du hast schon Interesse geweckt. Mit Plus siehst du das ganze Profil.", viewPlus: "Plus ansehen", train: "Treffen", trainTitle: "Lernt euch bei euren Hobbys kennen", verifiedHost: "✓ Verifizierte Leitung", highParkRun: "High Park Morgenlauf", highParkDetails: "8:00 · Lockerer 5 km · 12 / 20 Personen", createEvent: "Öffentliche Aktivität erstellen", plusHostTools: "Plus-Organisationstools", myProfile: "Mein Profil", kevinSports: "Laufen · Tennis · Radfahren", kevinActivity: "4× / Woche · Fortgeschritten", editProfile: "Profil bearbeiten", settingsAccount: "Einstellungen & Konto", discoverTab: "Entdecken", meTab: "Ich", settings: "Einstellungen", accountPreferences: "Konto & Präferenzen", billing: "Abrechnung & Abo", privacy: "Datenschutz & Sportdaten", deleteAccount: "Konto löschen", logout: "Abmelden", language: "Sprache", languageTitle: "Anzeigesprache", languageCaption: "Wähle die Sprache von PACE", close: "Schließen", plusTitle: "Mach den ersten Schritt", plusDescription: "Mit Plus siehst du, wer dich mag, kannst schon vor einem Match einladen und eigene Aktivitäten organisieren.", manageCancel: "14,99 $ / Monat · Verwalten oder kündigen in Einstellungen & Konto", priceMonthly: "14,99 $ / Monat", subscribePlus: "Plus abonnieren", filterApplied: "Distanz- und Sportpräferenzen angewendet.",
  },
};

// Empty discovery copy keeps the tone light and leaves recovery to the filters already on screen.
Object.assign(translations["zh-CN"], { networkGrowing: "还没遇见合适的人", cityOpening: "换个范围，继续认识", waitlistText: "附近暂时没有符合这些条件的人。试试其他运动，或扩大距离，给相识多一点可能。" });
Object.assign(translations.en, { networkGrowing: "Still looking for your kind of person", cityOpening: "Make room for someone new", waitlistText: "No one nearby matches these filters yet. Try another sport or widen your distance to meet more people." });
Object.assign(translations.fr, { networkGrowing: "La bonne rencontre se fait attendre", cityOpening: "Ouvrez-vous à de nouvelles rencontres", waitlistText: "Personne à proximité ne correspond encore à ces filtres. Essayez un autre sport ou élargissez la distance." });
Object.assign(translations.es, { networkGrowing: "Esa conexión aún está por llegar", cityOpening: "Haz sitio para alguien nuevo", waitlistText: "Todavía nadie cerca coincide con estos filtros. Prueba otro deporte o amplía la distancia para conocer más personas." });
Object.assign(translations.de, { networkGrowing: "Dein nächstes Kennenlernen wartet noch", cityOpening: "Mach Platz für neue Begegnungen", waitlistText: "Noch passt niemand in deiner Nähe zu diesen Filtern. Probiere eine andere Sportart oder einen größeren Umkreis." });

// Product voice: sport is shared lifestyle context, while connection is the outcome.
Object.assign(translations["zh-CN"], { connectionTitle: "匹配", realLikes: "对你感兴趣", whoLikes: "想认识你的人", likesDescription: "看看谁已经对你心动。Plus 可查看完整资料。", editProfile: "编辑资料", profileOverview: "资料概览", identityVisible: "让彼此更安心地认识", sharedLifestyle: "共同爱好，是故事的开场", plusTitle: "让相识更进一步" });
Object.assign(translations.en, { connectionTitle: "Matches", realLikes: "INTEREST", whoLikes: "People who liked you", likesDescription: "Someone’s already interested. See their full profile with Plus.", editProfile: "Edit profile", profileOverview: "Profile overview", identityVisible: "A little reassurance before you say hello", sharedLifestyle: "Shared interests. A place to start.", plusTitle: "Make the first move" });
Object.assign(translations.fr, { connectionTitle: "Matchs", realLikes: "INTÉRÊT", whoLikes: "Les personnes qui vous aiment", likesDescription: "Vous avez déjà attiré son attention. Découvrez son profil complet avec Plus.", editProfile: "Modifier le profil", profileOverview: "Aperçu du profil", identityVisible: "Un peu de confiance avant le premier bonjour", sharedLifestyle: "Des passions communes pour commencer." });
Object.assign(translations.es, { connectionTitle: "Matches", realLikes: "INTERÉS", whoLikes: "Personas a las que les gustas", likesDescription: "Ya has despertado interés. Mira su perfil completo con Plus.", editProfile: "Editar perfil", profileOverview: "Resumen del perfil", identityVisible: "Un poco de confianza antes del primer hola", sharedLifestyle: "Intereses en común para empezar." });
Object.assign(translations.de, { connectionTitle: "Matches", realLikes: "INTERESSE", whoLikes: "Menschen, die dich mögen", likesDescription: "Du hast schon Interesse geweckt. Mit Plus siehst du das ganze Profil.", editProfile: "Profil bearbeiten", profileOverview: "Profilübersicht", identityVisible: "Ein gutes Gefühl vor dem ersten Hallo", sharedLifestyle: "Gemeinsame Interessen als Anfang." });

// Interactive labels follow the selected interface language, including screen-reader-only controls.
Object.assign(translations["zh-CN"], { directInviteHint: "尚未匹配时的运动邀约是 PACE Plus 会员权益。", appLabel: "PACE 运动交友应用", home: "PACE 首页", notifications: "通知", sportFilters: "运动筛选", skipProfile: "跳过此资料", trainingIntent: "约 TA 一起运动", likeProfile: "喜欢此资料", mayaAvatar: "Maya 的头像", mainNavigation: "主导航", chatConversation: "聊天" });
Object.assign(translations.en, { directInviteHint: "Inviting before a match is included with PACE Plus.", appLabel: "PACE sport dating app", home: "PACE home", notifications: "Notifications", sportFilters: "Sport filters", skipProfile: "Pass on this profile", trainingIntent: "Invite to meet", likeProfile: "Like this profile", mayaAvatar: "Maya profile photo", mainNavigation: "Main navigation", chatConversation: "Chat conversation" });
Object.assign(translations.fr, { directInviteHint: "Inviter avant un match est un avantage PACE Plus.", appLabel: "Application PACE de rencontres sportives", home: "Accueil PACE", notifications: "Notifications", sportFilters: "Filtres sportifs", skipProfile: "Passer ce profil", trainingIntent: "Proposer une sortie", likeProfile: "Aimer ce profil", mayaAvatar: "Photo de profil de Maya", mainNavigation: "Navigation principale", chatConversation: "Conversation" });
Object.assign(translations.es, { directInviteHint: "Invitar antes de hacer match está incluido en PACE Plus.", appLabel: "PACE, una app de citas a través del deporte", home: "Inicio de PACE", notifications: "Notificaciones", sportFilters: "Filtros de deporte", skipProfile: "Pasar este perfil", trainingIntent: "Proponer un plan", likeProfile: "Me gusta este perfil", mayaAvatar: "Foto de perfil de Maya", mainNavigation: "Navegación principal", chatConversation: "Conversación" });
Object.assign(translations.de, { directInviteHint: "Einladungen vor einem Match sind bei PACE Plus enthalten.", appLabel: "PACE Dating-App für aktive Menschen", home: "PACE Startseite", notifications: "Benachrichtigungen", sportFilters: "Sportfilter", skipProfile: "Profil überspringen", trainingIntent: "Ein Treffen vorschlagen", likeProfile: "Profil liken", mayaAvatar: "Mayas Profilfoto", mainNavigation: "Hauptnavigation", chatConversation: "Unterhaltung" });

Object.assign(translations["zh-CN"], { requestFailed: "暂时无法完成，请稍后重试。" });
Object.assign(translations.en, { requestFailed: "Couldn’t complete that. Please try again." });
Object.assign(translations.fr, { requestFailed: "Impossible de terminer. Réessayez." });
Object.assign(translations.es, { requestFailed: "No se pudo completar. Inténtalo de nuevo." });
Object.assign(translations.de, { requestFailed: "Das hat nicht geklappt. Bitte versuche es erneut." });

Object.assign(translations["zh-CN"], { momentsTab: "动态", momentsEyebrow: "多了解一点", momentsTitle: "彼此的日常", connectionsOnly: "仅匹配对象可见", momentsIntro: "从一次出发、一条路线、一个小瞬间，慢慢了解你的匹配对象。", publishMoment: "发布动态" });
Object.assign(translations.en, { momentsTab: "Moments", momentsEyebrow: "BEYOND THE PROFILE", momentsTitle: "A little more you", connectionsOnly: "Your matches only", momentsIntro: "Get to know your matches through the adventures, little wins, and everyday moments they share.", publishMoment: "Share a moment" });
Object.assign(translations.fr, { momentsTab: "Moments", momentsEyebrow: "AU-DELÀ DU PROFIL", momentsTitle: "Un peu plus de vous", connectionsOnly: "Vos matchs uniquement", momentsIntro: "Découvrez vos matchs à travers leurs aventures, petites victoires et moments du quotidien.", publishMoment: "Partager un moment" });
Object.assign(translations.es, { momentsTab: "Momentos", momentsEyebrow: "MÁS ALLÁ DEL PERFIL", momentsTitle: "Un poco más de ti", connectionsOnly: "Solo tus matches", momentsIntro: "Conoce mejor a tus matches a través de sus aventuras, pequeños logros y momentos cotidianos.", publishMoment: "Compartir un momento" });
Object.assign(translations.de, { momentsTab: "Momente", momentsEyebrow: "MEHR ALS EIN PROFIL", momentsTitle: "Ein bisschen mehr du", connectionsOnly: "Nur deine Matches", momentsIntro: "Lerne deine Matches durch ihre Abenteuer, kleinen Erfolge und Alltagsmomente besser kennen.", publishMoment: "Moment teilen" });
Object.assign(translations["zh-CN"], { mayaSchedule: "周末可约", mayaGoal: "备战赛事" });
Object.assign(translations.en, { mayaSchedule: "Available weekends", mayaGoal: "Training for an event" });
Object.assign(translations.fr, { mayaSchedule: "Disponible le week-end", mayaGoal: "Prépare une compétition" });
Object.assign(translations.es, { mayaSchedule: "Disponible los fines de semana", mayaGoal: "Preparando una competición" });
Object.assign(translations.de, { mayaSchedule: "Am Wochenende verfügbar", mayaGoal: "Training für einen Wettkampf" });
Object.assign(translations["zh-CN"], { previousPhoto: "上一张照片", nextPhoto: "下一张照片", photoCount: (current, total) => `${current} / ${total} 张照片` });
Object.assign(translations.en, { previousPhoto: "Previous photo", nextPhoto: "Next photo", photoCount: (current, total) => `Photo ${current} of ${total}` });
Object.assign(translations.fr, { previousPhoto: "Photo précédente", nextPhoto: "Photo suivante", photoCount: (current, total) => `Photo ${current} sur ${total}` });
Object.assign(translations.es, { previousPhoto: "Foto anterior", nextPhoto: "Foto siguiente", photoCount: (current, total) => `Foto ${current} de ${total}` });
Object.assign(translations.de, { previousPhoto: "Vorheriges Foto", nextPhoto: "Nächstes Foto", photoCount: (current, total) => `Foto ${current} von ${total}` });

export const matchSuccessCopy = {
  "zh-CN": { kicker: "新的匹配", title: "你们互相喜欢", description: "Maya 也想认识你", chat: "开始聊聊", close: "暂时关闭匹配成功提示" },
  en: { kicker: "NEW MATCH", title: "You matched", description: "Maya wants to meet you too", chat: "Start the conversation", close: "Close match success" },
  fr: { kicker: "NOUVEAU MATCH", title: "C’est un match", description: "Maya veut aussi vous connaître", chat: "Commencer à discuter", close: "Fermer la connexion" },
  es: { kicker: "NUEVO MATCH", title: "Hay match", description: "Maya también quiere conocerte", chat: "Empezar a hablar", close: "Cerrar conexión" },
  de: { kicker: "NEUES MATCH", title: "Ihr habt ein Match", description: "Maya möchte dich auch kennenlernen", chat: "Gespräch starten", close: "Verbindung schließen" },
};

export const sportLabels = {
  "zh-CN": { running: "跑步", cycling: "骑行", strength: "力量训练", weekly: "每周运动" },
  en: { running: "Running", cycling: "Cycling", strength: "Strength", weekly: "Activities / week" },
  fr: { running: "Course", cycling: "Vélo", strength: "Musculation", weekly: "Activités / semaine" },
  es: { running: "Running", cycling: "Ciclismo", strength: "Fuerza", weekly: "Actividades / semana" },
  de: { running: "Laufen", cycling: "Radfahren", strength: "Krafttraining", weekly: "Aktivitäten / Woche" },
};

export const otherSportLabels = { "zh-CN": "其他", en: "Others", fr: "Autres", es: "Otros", de: "Weitere" };
export const singleSportText = {
  "zh-CN": "选择一项运动，认识同样把它作为主要爱好的人。",
  en: "Choose a sport to meet people who share it as a main interest.",
  fr: "Choisissez un sport pour rencontrer des personnes qui en partagent la passion.",
  es: "Elige un deporte para conocer a quienes lo comparten como interés principal.",
  de: "Wähle eine Sportart, um Menschen kennenzulernen, die deine Begeisterung dafür teilen.",
};
export const sportCatalogCopy = {
  "zh-CN": { search: "搜索运动项目", count: (total) => `${total} 个热门运动项目` },
  en: { search: "Search sports", count: (total) => `${total} popular sports` },
  fr: { search: "Rechercher un sport", count: (total) => `${total} sports populaires` },
  es: { search: "Buscar deportes", count: (total) => `${total} deportes populares` },
  de: { search: "Sportarten suchen", count: (total) => `${total} beliebte Sportarten` },
};

export const momentsCopy = {
  "zh-CN": { like: "点赞", unlike: "取消点赞", comments: "评论", message: "聊天", commentTitle: "评论", placeholder: "打个招呼，或聊聊你也想去的地方…", send: "发送", profile: "查看匹配对象的资料", connected: "你们已匹配", sessions: "本周运动", composeEyebrow: "让彼此更熟悉", composeTitle: "分享一个瞬间", caption: "今天去了哪里，有什么值得分享？", sport: "运动项目", sportPlaceholder: "填写运动，例如：跑步、攀岩", addPhoto: "添加照片", details: "补充活动数据（可选 · 最多 3 项）", metric: "指标", metricPlaceholder: "例如：用时、组数、难度、比分", result: "结果", resultPlaceholder: "例如：45 分钟、5×5、V5、3–1", addMetric: "添加一项", metricLimit: "已添加 3 项", publish: "分享", published: "动态已分享给你的匹配对象。", photoHint: "照片数量不限 · 每张最大 10 MB", removePhoto: "移除照片" },
  en: { like: "Like", unlike: "Unlike", comments: "Comments", message: "Chat", commentTitle: "Comments", placeholder: "Say hello, ask a question, or share a little encouragement…", send: "Send", profile: "View match profile", connected: "You matched", sessions: "activities this week", composeEyebrow: "A LITTLE MORE YOU", composeTitle: "Share a moment", caption: "Where did you go, and what made you smile?", sport: "Sport", sportPlaceholder: "Type a sport, e.g. running or climbing", addPhoto: "Add photos", details: "Add activity details (optional · up to 3)", metric: "Metric", metricPlaceholder: "Time, sets, grade, score…", result: "Result", resultPlaceholder: "45 min, 5×5, V5, 3–1…", addMetric: "Add metric", metricLimit: "3 metrics added", publish: "Share", published: "Your moment is now visible to your matches.", photoHint: "Any number of photos · 10 MB each", removePhoto: "Remove photo" },
  fr: { like: "J’aime", unlike: "Je n’aime plus", comments: "Commentaires", message: "Discuter", commentTitle: "Commentaires", placeholder: "Un bonjour, une question ou un petit encouragement…", send: "Envoyer", profile: "Voir le profil du match", connected: "Vous avez un match", sessions: "activités cette semaine", composeEyebrow: "UN PEU PLUS DE VOUS", composeTitle: "Partager un moment", caption: "Où êtes-vous allé·e, et qu’est-ce qui vous a fait sourire ?", sport: "Sport", sportPlaceholder: "Saisissez un sport, ex. course", addPhoto: "Ajouter des photos", details: "Ajouter des données (facultatif · 3 max.)", metric: "Indicateur", metricPlaceholder: "Temps, séries, niveau, score…", result: "Résultat", resultPlaceholder: "45 min, 5×5, V5, 3–1…", addMetric: "Ajouter", metricLimit: "3 indicateurs ajoutés", publish: "Partager", published: "Votre moment est visible par vos matchs.", photoHint: "Photos illimitées · 10 Mo chacune", removePhoto: "Supprimer la photo" },
  es: { like: "Me gusta", unlike: "Ya no me gusta", comments: "Comentarios", message: "Chat", commentTitle: "Comentarios", placeholder: "Saluda, pregunta algo o comparte unas palabras de ánimo…", send: "Enviar", profile: "Ver perfil del match", connected: "Han hecho match", sessions: "actividades esta semana", composeEyebrow: "UN POCO MÁS DE TI", composeTitle: "Compartir un momento", caption: "¿Adónde fuiste y qué te hizo sonreír?", sport: "Deporte", sportPlaceholder: "Escribe un deporte, p. ej. running", addPhoto: "Añadir fotos", details: "Añadir datos (opcional · máximo 3)", metric: "Métrica", metricPlaceholder: "Tiempo, series, grado, marcador…", result: "Resultado", resultPlaceholder: "45 min, 5×5, V5, 3–1…", addMetric: "Añadir métrica", metricLimit: "3 métricas añadidas", publish: "Compartir", published: "Tu momento ya está visible para tus matches.", photoHint: "Fotos ilimitadas · 10 MB cada una", removePhoto: "Eliminar foto" },
  de: { like: "Gefällt mir", unlike: "Gefällt mir nicht mehr", comments: "Kommentare", message: "Chat", commentTitle: "Kommentare", placeholder: "Sag Hallo, stell eine Frage oder mach ein Kompliment…", send: "Senden", profile: "Match-Profil ansehen", connected: "Ihr habt ein Match", sessions: "Aktivitäten diese Woche", composeEyebrow: "EIN BISSCHEN MEHR DU", composeTitle: "Einen Moment teilen", caption: "Wo warst du, und was hat dich zum Lächeln gebracht?", sport: "Sportart", sportPlaceholder: "Sportart eingeben, z. B. Laufen", addPhoto: "Fotos hinzufügen", details: "Aktivitätsdetails (optional · max. 3)", metric: "Messwert", metricPlaceholder: "Zeit, Sätze, Grad, Ergebnis…", result: "Ergebnis", resultPlaceholder: "45 Min., 5×5, V5, 3–1…", addMetric: "Messwert hinzufügen", metricLimit: "3 Messwerte hinzugefügt", publish: "Teilen", published: "Dein Moment ist für deine Matches sichtbar.", photoHint: "Beliebig viele Fotos · je 10 MB", removePhoto: "Foto entfernen" },
};

Object.assign(momentsCopy["zh-CN"], { photoAlt: "分享的瞬间", noComments: "暂无评论", dismissComments: "关闭评论", dismissHint: "向下拖动顶部把手，或轻点把手关闭评论。" });
Object.assign(momentsCopy.en, { photoAlt: "Shared moment", noComments: "No comments", commentTitle: "Comments", composeEyebrow: "A LITTLE MORE YOU", caption: "Where did you go, and what made you smile?", dismissComments: "Close comments", dismissHint: "Drag the top handle down, or tap it, to close comments." });
Object.assign(momentsCopy.fr, { photoAlt: "Moment partagé", noComments: "Aucun commentaire", dismissComments: "Fermer les commentaires", dismissHint: "Faites glisser la poignée vers le bas, ou touchez-la, pour fermer." });
Object.assign(momentsCopy.es, { photoAlt: "Momento compartido", noComments: "No hay comentarios", dismissComments: "Cerrar comentarios", dismissHint: "Arrastra el tirador superior hacia abajo, o tócalo, para cerrar." });
Object.assign(momentsCopy.de, { photoAlt: "Geteilter Moment", noComments: "Keine Kommentare", dismissComments: "Kommentare schließen", dismissHint: "Ziehe den oberen Griff nach unten oder tippe darauf, um zu schließen." });

export const swipeLabels = {
  "zh-CN": { like: "喜欢", skip: "跳过" },
  en: { like: "LIKE", skip: "PASS" },
  fr: { like: "J’AIME", skip: "PASSER" },
  es: { like: "ME GUSTA", skip: "PASAR" },
  de: { like: "GEFÄLLT", skip: "WEITER" },
};

export const languageNames = { "zh-CN": "简体中文", en: "English", fr: "Français", es: "Español", de: "Deutsch" };
export const profileCopy = {
  "zh-CN": { eyebrow: "编辑资料", title: "你的资料", sports: "选择运动项目", frequency: "每周运动次数", bio: "简介（可留空）", bioPlaceholder: "聊聊你的周末、喜欢的事，以及想认识怎样的人", photos: "照片", save: "保存资料", photoLimit: "最多 6 张照片", custom: "添加其他运动（可选）", customPlaceholder: "例如：冲浪、壁球", saved: "资料已保存", options: ["跑步", "骑行", "网球", "攀岩", "游泳", "力量训练", "瑜伽", "足球", "滑雪", "高尔夫"] },
  en: { eyebrow: "Edit profile", title: "Your profile", sports: "Choose your sports", frequency: "Activities per week", bio: "Bio (optional)", bioPlaceholder: "Your ideal weekend, little obsessions, and who you’d love to meet", photos: "Photos", save: "Save profile", photoLimit: "Up to 6 photos", custom: "Add another sport (optional)", customPlaceholder: "e.g. Surfing, squash", saved: "Profile saved", options: ["Running", "Cycling", "Tennis", "Climbing", "Swimming", "Strength training", "Yoga", "Football", "Skiing", "Golf"] },
  fr: { eyebrow: "Modifier le profil", title: "Votre profil", sports: "Choisissez vos sports", frequency: "Activités par semaine", bio: "Bio (facultatif)", bioPlaceholder: "Votre week-end idéal, vos passions et qui vous aimeriez rencontrer", photos: "Photos", save: "Enregistrer", photoLimit: "Jusqu’à 6 photos", custom: "Ajouter un autre sport (facultatif)", customPlaceholder: "ex. Surf, squash", saved: "Profil enregistré", options: ["Course", "Vélo", "Tennis", "Escalade", "Natation", "Musculation", "Yoga", "Football", "Ski", "Golf"] },
  es: { eyebrow: "Editar perfil", title: "Tu perfil", sports: "Elige tus deportes", frequency: "Actividades por semana", bio: "Bio (opcional)", bioPlaceholder: "Tu fin de semana ideal, lo que te apasiona y a quién te gustaría conocer", photos: "Fotos", save: "Guardar perfil", photoLimit: "Hasta 6 fotos", custom: "Añadir otro deporte (opcional)", customPlaceholder: "p. ej., Surf, squash", saved: "Perfil guardado", options: ["Running", "Ciclismo", "Tenis", "Escalada", "Natación", "Fuerza", "Yoga", "Fútbol", "Esquí", "Golf"] },
  de: { eyebrow: "Profil bearbeiten", title: "Dein Profil", sports: "Wähle deine Sportarten", frequency: "Aktivitäten pro Woche", bio: "Bio (optional)", bioPlaceholder: "Dein perfektes Wochenende, kleine Leidenschaften und wen du gern kennenlernen würdest", photos: "Fotos", save: "Profil speichern", photoLimit: "Bis zu 6 Fotos", custom: "Weitere Sportart hinzufügen (optional)", customPlaceholder: "z. B. Surfen, Squash", saved: "Profil gespeichert", options: ["Laufen", "Radfahren", "Tennis", "Klettern", "Schwimmen", "Krafttraining", "Yoga", "Fußball", "Skifahren", "Golf"] },
};

Object.assign(profileCopy["zh-CN"], { height: "身高（可选）", heightUnit: "身高单位", centimetres: "厘米", feetAndInches: "英尺 / 英寸", heightCm: "身高（厘米）", heightFeet: "英尺", heightInches: "英寸", ethnicity: "族裔（可选）", ethnicityPlaceholder: "若想填写，可在这里添加", visibility: "在发现卡上展示", showHeight: "展示身高", showEthnicity: "展示族裔", visibleDetails: "你的发现卡会展示", noVisibleDetails: "尚未公开任何个人信息" });
Object.assign(profileCopy.en, { height: "Height (optional)", heightUnit: "Height unit", centimetres: "Centimetres", feetAndInches: "Feet / inches", heightCm: "Height in centimetres", heightFeet: "Feet", heightInches: "Inches", ethnicity: "Ethnicity (optional)", ethnicityPlaceholder: "Add if you want to", visibility: "Show on your discovery card", showHeight: "Show height", showEthnicity: "Show ethnicity", visibleDetails: "Visible on your discovery card", noVisibleDetails: "No personal details are visible" });
Object.assign(profileCopy.fr, { height: "Taille (facultatif)", heightUnit: "Unité de taille", centimetres: "Centimètres", feetAndInches: "Pieds / pouces", heightCm: "Taille en centimètres", heightFeet: "Pieds", heightInches: "Pouces", ethnicity: "Origines (facultatif)", ethnicityPlaceholder: "Ajoutez si vous le souhaitez", visibility: "Afficher sur votre carte", showHeight: "Afficher la taille", showEthnicity: "Afficher les origines", visibleDetails: "Visible sur votre carte de découverte", noVisibleDetails: "Aucun détail personnel n’est visible" });
Object.assign(profileCopy.es, { height: "Estatura (opcional)", heightUnit: "Unidad de estatura", centimetres: "Centímetros", feetAndInches: "Pies / pulgadas", heightCm: "Estatura en centímetros", heightFeet: "Pies", heightInches: "Pulgadas", ethnicity: "Origen étnico (opcional)", ethnicityPlaceholder: "Añádelo si quieres", visibility: "Mostrar en tu tarjeta", showHeight: "Mostrar estatura", showEthnicity: "Mostrar origen étnico", visibleDetails: "Visible en tu tarjeta de descubrimiento", noVisibleDetails: "No hay datos personales visibles" });
Object.assign(profileCopy.de, { height: "Körpergröße (optional)", heightUnit: "Größeneinheit", centimetres: "Zentimeter", feetAndInches: "Fuß / Zoll", heightCm: "Größe in Zentimetern", heightFeet: "Fuß", heightInches: "Zoll", ethnicity: "Ethnische Zugehörigkeit (optional)", ethnicityPlaceholder: "Bei Bedarf hinzufügen", visibility: "Auf deiner Entdeckungskarte zeigen", showHeight: "Körpergröße zeigen", showEthnicity: "Ethnische Zugehörigkeit zeigen", visibleDetails: "Sichtbar auf deiner Entdeckungskarte", noVisibleDetails: "Keine persönlichen Angaben sichtbar" });

Object.assign(profileCopy["zh-CN"], { eyebrow: "编辑资料", title: "你的资料", bioPlaceholder: "聊聊你的周末、喜欢的事，以及想认识怎样的人", saved: "资料已保存" });
Object.assign(profileCopy.en, { eyebrow: "Edit profile", title: "Your profile", bioPlaceholder: "Your ideal weekend, little obsessions, and who you’d love to meet", saved: "Profile saved" });
Object.assign(profileCopy.fr, { eyebrow: "Modifier le profil", title: "Votre profil", saved: "Profil enregistré" });
Object.assign(profileCopy.es, { eyebrow: "Editar perfil", title: "Tu perfil", saved: "Perfil guardado" });
Object.assign(profileCopy.de, { eyebrow: "Profil bearbeiten", title: "Dein Profil", saved: "Profil gespeichert" });

Object.assign(profileCopy["zh-CN"], { cancel: "取消", done: "完成", edit: "编辑", preview: "预览", editorSections: "资料编辑页面", sportsHelp: "你喜欢哪些运动，也想和有好感的人一起尝试？", aboutYou: "关于你", aboutHelp: "分享你的个性、日常，以及想与怎样的人产生默契。", personalDetails: "个人信息", addPhoto: "添加照片", removePhoto: "移除照片", photoAlt: "Kevin 的资料照片", sportsRequired: "请至少选择一项运动。" });
Object.assign(profileCopy.en, { cancel: "Cancel", done: "Done", edit: "Edit", preview: "View", editorSections: "Profile editor sections", sportsHelp: "Choose the sports you love and would like to share with someone.", aboutYou: "About you", aboutHelp: "Share what makes you you, and who you’d love to meet.", personalDetails: "Personal details", addPhoto: "Add photo", removePhoto: "Remove photo", photoAlt: "Kevin profile photo", sportsRequired: "Choose at least one sport." });
Object.assign(profileCopy.fr, { cancel: "Annuler", done: "Terminé", edit: "Modifier", preview: "Voir", editorSections: "Sections du profil", sportsHelp: "Choisissez les sports que vous aimez et aimeriez partager avec quelqu’un.", aboutYou: "À propos", aboutHelp: "Racontez ce qui vous rend unique et qui vous aimeriez rencontrer.", personalDetails: "Informations personnelles", addPhoto: "Ajouter", removePhoto: "Supprimer la photo", photoAlt: "Photo de profil de Kevin", sportsRequired: "Choisissez au moins un sport." });
Object.assign(profileCopy.es, { cancel: "Cancelar", done: "Listo", edit: "Editar", preview: "Ver", editorSections: "Secciones del perfil", sportsHelp: "Elige los deportes que te gustan y querrías compartir con alguien.", aboutYou: "Sobre ti", aboutHelp: "Cuenta qué te hace ser tú y a quién te gustaría conocer.", personalDetails: "Datos personales", addPhoto: "Añadir", removePhoto: "Eliminar foto", photoAlt: "Foto de perfil de Kevin", sportsRequired: "Elige al menos un deporte." });
Object.assign(profileCopy.de, { cancel: "Abbrechen", done: "Fertig", edit: "Bearbeiten", preview: "Ansehen", editorSections: "Profilbereiche", sportsHelp: "Wähle Sportarten, die du liebst und gern mit jemandem teilen würdest.", aboutYou: "Über dich", aboutHelp: "Erzähl, was dich ausmacht und wen du gern kennenlernen würdest.", personalDetails: "Persönliche Angaben", addPhoto: "Foto hinzufügen", removePhoto: "Foto entfernen", photoAlt: "Kevins Profilfoto", sportsRequired: "Wähle mindestens eine Sportart." });

export const discoveryFilterCopy = {
  "zh-CN": { eyebrow: "发现筛选", sportTitle: "选择运动项目", sportText: "选择一项运动，寻找主要参与这项运动的人；选择全部运动可取消限制。", apply: "应用运动筛选", all: "全部运动", prefsTitle: "筛选偏好", prefsText: "从共同爱好和能见面的时间，找到更合拍的人。", goal: "相处方式", schedule: "方便见面的时间", goals: ["轻松运动", "一起备战赛事", "认识新朋友"], schedules: ["工作日", "周末", "时间灵活"], save: "保存偏好", applied: "发现偏好已更新" },
  en: { eyebrow: "Discovery filters", sportTitle: "Choose sports", sportText: "Choose one sport to meet people who mainly enjoy it, or choose All sports.", apply: "Apply sport filter", all: "All sports", prefsTitle: "Filter preferences", prefsText: "Find common ground, and a time you could spend together.", goal: "What brings you out?", schedule: "Time to meet", goals: ["A relaxed outing", "Training for an event", "Meeting new people"], schedules: ["Weekdays", "Weekends", "Flexible"], save: "Save preferences", applied: "Discovery preferences updated" },
  fr: { eyebrow: "Filtres de découverte", sportTitle: "Choisir les sports", sportText: "Choisissez un sport pour rencontrer des personnes qui le pratiquent principalement, ou tous les sports.", apply: "Appliquer les sports", all: "Tous les sports", prefsTitle: "Préférences", prefsText: "Trouvez des affinités et un moment à partager.", goal: "Ce qui vous motive", schedule: "Disponibilité pour se voir", goals: ["Une sortie tranquille", "Préparer une compétition", "Faire de nouvelles rencontres"], schedules: ["Semaine", "Week-end", "Flexible"], save: "Enregistrer", applied: "Préférences mises à jour" },
  es: { eyebrow: "Filtros de descubrimiento", sportTitle: "Elegir deportes", sportText: "Elige un deporte para conocer a quienes lo practican principalmente, o elige todos.", apply: "Aplicar deportes", all: "Todos los deportes", prefsTitle: "Preferencias", prefsText: "Encuentra intereses en común y tiempo para compartirlos.", goal: "¿Qué te anima a salir?", schedule: "Tiempo para verse", goals: ["Un plan tranquilo", "Preparar un evento", "Conocer gente nueva"], schedules: ["Entre semana", "Fin de semana", "Flexible"], save: "Guardar", applied: "Preferencias actualizadas" },
  de: { eyebrow: "Entdeckungsfilter", sportTitle: "Sportarten wählen", sportText: "Wähle eine Sportart, um Menschen mit diesem Schwerpunkt kennenzulernen, oder alle Sportarten.", apply: "Sportfilter anwenden", all: "Alle Sportarten", prefsTitle: "Filtereinstellungen", prefsText: "Findet Gemeinsamkeiten und Zeit füreinander.", goal: "Was bringt dich raus?", schedule: "Zeit für ein Treffen", goals: ["Ein entspannter Ausflug", "Für ein Event trainieren", "Neue Leute kennenlernen"], schedules: ["Wochentags", "Wochenende", "Flexibel"], save: "Speichern", applied: "Einstellungen aktualisiert" },
};

export const flowCopy = {
  "zh-CN": {
    chat: { eyebrow: "Maya · 从共同爱好开始", title: "第一句，聊点什么？", verified: "✓ 双方自拍已认证", summary: "Maya · 每周运动 3–4 次", note: "你们已经有了共同点。打个招呼，或约一次见面。", invite: "约 TA 一起运动", inviteHint: "选个项目、时间和地点", normalChat: "嗨，Maya 👋", message: "消息", placeholder: "例如：你周日想一起慢跑吗？", send: "发送文字消息" },
    invite: { eyebrow: "从聊天到见面", title: "约 TA 一起运动", sport: "运动项目", sportPlaceholder: "例如：跑步 · 轻松 5K", date: "日期", time: "时间", place: "地点", placeValue: "High Park 南门", notes: "备注（可选）", notePlaceholder: "配速、见面提示，或运动后的咖啡计划", send: "邀请", sent: "邀约已发送给 Maya" },
    billing: { eyebrow: "账单与订阅", title: "订阅管理", current: "当前订阅", benefits: "查看谁喜欢你 · 匹配前发出邀约 · 组织公开活动", accessUntil: "权益截至", nextCharge: "下次扣款", afterExpiry: "到期后价格", chargeAmount: "扣款金额", cancelled: "已取消续费", cancelledHint: "权益保留至到期日", cancel: "取消订阅", cancellationToast: "续费已取消；权益保留至", cancellationTail: "，营销通知已停止。" },
    privacy: { eyebrow: "隐私与数据", title: "可信，但不过度暴露", text: "公开资料只展示自拍认证状态、运动类型与训练摘要；不会展示精确路线或住址。", selfie: "自拍活体认证", passed: "已通过", connected: "已连接", connect: "连接 ›", notConnected: "未连接" },
    deletion: { eyebrow: "账户删除", title: "注销 PACE 账户", text: "账户和资料将被删除。确认后，PACE 不会再向你发送任何营销通知或邮件。", confirm: "删除我的账户", done: "账户已删除；营销投递已永久停止。" },
    toast: { messageSent: "消息已发送", liked: "已发送真实 Like。若对方也喜欢你，才会匹配。", skipped: "已跳过此资料", waitlist: "已加入 Toronto 等待名单；开放时会通知你。", notifications: "暂时没有新通知" },
  },
  en: {
    chat: { eyebrow: "Maya · Something in common", title: "Start with a hello", verified: "✓ Both selfie verified", summary: "Maya · Active 3–4× / week", note: "You’ve found something in common. Say hello or make a plan.", invite: "Make a plan", inviteHint: "Pick a sport, a time, a place", normalChat: "Hey Maya 👋", message: "Message", placeholder: "For example: Would you like to do an easy run on Sunday?", send: "Send message" },
    invite: { eyebrow: "TAKE IT OFF THE CHAT", title: "Make a plan", sport: "Sport", sportPlaceholder: "e.g. Running · Easy 5K", date: "Date", time: "Time", place: "Location", placeValue: "High Park south entrance", notes: "Notes (optional)", notePlaceholder: "Pace, meeting details, or coffee afterwards", send: "Invite", sent: "Invite sent to Maya" },
    billing: { eyebrow: "Billing & subscription", title: "Manage subscription", current: "Current subscription", benefits: "See who likes you · Invite before matching · Host public activities", accessUntil: "Access until", nextCharge: "Next charge", afterExpiry: "Price after expiry", chargeAmount: "Charge amount", cancelled: "Renewal cancelled", cancelledHint: "Access stays active until expiry", cancel: "Cancel subscription", cancellationToast: "Renewal cancelled; access remains until ", cancellationTail: ". Marketing notifications are now stopped." },
    privacy: { eyebrow: "Privacy & data", title: "Trusted, not overexposed", text: "Your public profile shows verification, sports, and training summaries—not precise routes or your address.", selfie: "Selfie liveness verification", passed: "Passed", connected: "Connected", connect: "Connect ›", notConnected: "Not connected" },
    deletion: { eyebrow: "Account deletion", title: "Delete PACE account", text: "Your account and profile will be deleted. After confirmation, PACE will no longer send marketing notifications or emails.", confirm: "Delete my account", done: "Account deleted; marketing delivery has permanently stopped." },
    toast: { messageSent: "Message sent", liked: "Like sent. A match is created only if Maya likes you too.", skipped: "Profile skipped", waitlist: "You joined the Toronto waitlist. We’ll let you know when it opens.", notifications: "No new notifications" },
  },
  fr: {
    chat: { eyebrow: "Maya · Un point commun", title: "Tout commence par un bonjour", verified: "✓ Selfies tous deux vérifiés", summary: "Maya · Active 3–4× / semaine", note: "Vous avez déjà un point commun. Dites bonjour ou proposez une sortie.", invite: "Proposer une sortie", inviteHint: "Un sport, une heure, un lieu", normalChat: "Salut Maya 👋", message: "Message", placeholder: "Par exemple : une course tranquille dimanche ?", send: "Envoyer le message" },
    invite: { eyebrow: "DU CHAT À LA RENCONTRE", title: "Proposer une sortie", sport: "Sport", sportPlaceholder: "Ex. Course · 5 km tranquille", date: "Date", time: "Heure", place: "Lieu", placeValue: "Entrée sud de High Park", notes: "Notes (facultatif)", notePlaceholder: "Allure, point de rendez-vous ou café après", send: "Inviter", sent: "Invitation envoyée à Maya" },
    billing: { eyebrow: "Facturation et abonnement", title: "Gérer l’abonnement", current: "Abonnement actuel", benefits: "Voir qui vous aime · Inviter avant le match · Organiser des activités", accessUntil: "Accès jusqu’au", nextCharge: "Prochain paiement", afterExpiry: "Prix après expiration", chargeAmount: "Montant", cancelled: "Renouvellement annulé", cancelledHint: "Accès maintenu jusqu’à l’expiration", cancel: "Annuler l’abonnement", cancellationToast: "Renouvellement annulé ; accès maintenu jusqu’au ", cancellationTail: ". Les notifications marketing sont arrêtées." },
    privacy: { eyebrow: "Confidentialité et données", title: "Fiable, sans surexposition", text: "Votre profil public affiche la vérification, les sports et un résumé d’entraînement, jamais vos itinéraires précis ni votre adresse.", selfie: "Vérification par selfie", passed: "Validé", connected: "Connecté", connect: "Connecter ›", notConnected: "Non connecté" },
    deletion: { eyebrow: "Suppression du compte", title: "Supprimer le compte PACE", text: "Votre compte et votre profil seront supprimés. Après confirmation, PACE ne vous enverra plus de notifications ni d’e-mails marketing.", confirm: "Supprimer mon compte", done: "Compte supprimé ; les envois marketing sont définitivement arrêtés." },
    toast: { messageSent: "Message envoyé", liked: "J’aime envoyé. Une connexion existe seulement si Maya vous aime aussi.", skipped: "Profil ignoré", waitlist: "Vous avez rejoint la liste d’attente de Toronto.", notifications: "Aucune nouvelle notification" },
  },
  es: {
    chat: { eyebrow: "Maya · Algo en común", title: "Empieza con un hola", verified: "✓ Ambos con selfie verificado", summary: "Maya · Activa 3–4× / semana", note: "Ya tienen algo en común. Saluda o propón un plan.", invite: "Proponer un plan", inviteHint: "Un deporte, una hora, un lugar", normalChat: "Hola Maya 👋", message: "Mensaje", placeholder: "Por ejemplo: ¿un trote suave el domingo?", send: "Enviar mensaje" },
    invite: { eyebrow: "DEL CHAT AL ENCUENTRO", title: "Proponer un plan", sport: "Deporte", sportPlaceholder: "P. ej. Running · 5K suave", date: "Fecha", time: "Hora", place: "Lugar", placeValue: "Entrada sur de High Park", notes: "Notas (opcional)", notePlaceholder: "Ritmo, punto de encuentro o café después", send: "Invitar", sent: "Invitación enviada a Maya" },
    billing: { eyebrow: "Pagos y suscripción", title: "Gestionar suscripción", current: "Suscripción actual", benefits: "Ver a quién le gustas · Invitar antes del match · Organizar actividades", accessUntil: "Acceso hasta", nextCharge: "Próximo cobro", afterExpiry: "Precio tras vencer", chargeAmount: "Importe", cancelled: "Renovación cancelada", cancelledHint: "El acceso continúa hasta el vencimiento", cancel: "Cancelar suscripción", cancellationToast: "Renovación cancelada; acceso hasta ", cancellationTail: ". Las notificaciones de marketing se detuvieron." },
    privacy: { eyebrow: "Privacidad y datos", title: "Confiable, sin sobreexponer", text: "Tu perfil público muestra verificación, deportes y resúmenes de entrenamiento, nunca rutas exactas ni tu dirección.", selfie: "Verificación de selfie", passed: "Verificado", connected: "Conectado", connect: "Conectar ›", notConnected: "No conectado" },
    deletion: { eyebrow: "Eliminar cuenta", title: "Eliminar cuenta PACE", text: "Tu cuenta y perfil se eliminarán. Tras confirmar, PACE no volverá a enviarte notificaciones ni correos de marketing.", confirm: "Eliminar mi cuenta", done: "Cuenta eliminada; los envíos de marketing se detuvieron definitivamente." },
    toast: { messageSent: "Mensaje enviado", liked: "Me gusta enviado. Solo habrá match si Maya también indica que le gustas.", skipped: "Perfil omitido", waitlist: "Te uniste a la lista de espera de Toronto.", notifications: "No hay notificaciones nuevas" },
  },
  de: {
    chat: { eyebrow: "Maya · Etwas gemeinsam", title: "Ein Hallo als Anfang", verified: "✓ Beide Selfies verifiziert", summary: "Maya · 3–4× pro Woche aktiv", note: "Ihr habt schon etwas gemeinsam. Sag Hallo oder schlag ein Treffen vor.", invite: "Ein Treffen planen", inviteHint: "Eine Sportart, eine Zeit, ein Ort", normalChat: "Hi Maya 👋", message: "Nachricht", placeholder: "Zum Beispiel: Lust auf einen lockeren Lauf am Sonntag?", send: "Nachricht senden" },
    invite: { eyebrow: "VOM CHAT ZUM TREFFEN", title: "Ein Treffen planen", sport: "Sportart", sportPlaceholder: "Z. B. Laufen · lockere 5 km", date: "Datum", time: "Uhrzeit", place: "Ort", placeValue: "High Park Südeingang", notes: "Notizen (optional)", notePlaceholder: "Tempo, Treffpunkt oder ein Kaffee danach", send: "Einladen", sent: "Einladung an Maya gesendet" },
    billing: { eyebrow: "Abrechnung und Abo", title: "Abo verwalten", current: "Aktuelles Abo", benefits: "Sehen, wer dich mag · Vor dem Match einladen · Aktivitäten organisieren", accessUntil: "Zugang bis", nextCharge: "Nächste Abbuchung", afterExpiry: "Preis nach Ablauf", chargeAmount: "Betrag", cancelled: "Verlängerung gekündigt", cancelledHint: "Zugang bleibt bis zum Ablauf aktiv", cancel: "Abo kündigen", cancellationToast: "Verlängerung gekündigt; Zugang bleibt bis ", cancellationTail: ". Marketing-Benachrichtigungen sind jetzt deaktiviert." },
    privacy: { eyebrow: "Datenschutz und Daten", title: "Vertrauenswürdig, nicht überexponiert", text: "Dein öffentliches Profil zeigt Verifizierung, Sportarten und Trainingszusammenfassungen, nie genaue Routen oder deine Adresse.", selfie: "Selfie-Verifizierung", passed: "Bestanden", connected: "Verbunden", connect: "Verbinden ›", notConnected: "Nicht verbunden" },
    deletion: { eyebrow: "Konto löschen", title: "PACE-Konto löschen", text: "Dein Konto und Profil werden gelöscht. Nach der Bestätigung sendet PACE keine Marketing-E-Mails oder Benachrichtigungen mehr.", confirm: "Mein Konto löschen", done: "Konto gelöscht; Marketingversand dauerhaft gestoppt." },
    toast: { messageSent: "Nachricht gesendet", liked: "Like gesendet. Ein Match entsteht nur, wenn Maya dich ebenfalls mag.", skipped: "Profil übersprungen", waitlist: "Du bist der Toronto-Warteliste beigetreten.", notifications: "Keine neuen Benachrichtigungen" },
  },
};

export const verificationCopy = {
  "zh-CN": {
    label: "自拍认证", step: (current) => `${current} / 4`,
    pages: [
      { eyebrow: "建立真实连接", title: "完成真人认证", text: "用一段简短的视频自拍证明资料背后是真实的你。", points: ["只有你能完成自己的认证", "认证结果会作为资料徽章展示"], action: "继续" },
      { eyebrow: "认证原理", title: "我们如何验证", text: "系统会将视频自拍中的面部与个人资料照片进行比对，并进行活体检测。", points: ["审核所需截图会被加密保护", "不会公开你的自拍视频"], action: "继续" },
      { eyebrow: "隐私说明", title: "只验证，不追踪", text: "认证完成后不会保留自拍视频，也不会长期保存底层面部识别模板。", points: ["认证通常在 24 小时内完成", "你可以在隐私设置中查看状态"], action: "开始认证" },
      { eyebrow: "视频自拍", title: "准备好了吗？", text: "将脸部置于椭圆框内，保持光线充足，然后缓慢靠近镜头。", points: [], action: "我准备好了" },
    ],
    ready: "认证演示已准备就绪",
  },
  en: {
    label: "Selfie verification", step: (current) => `${current} / 4`,
    pages: [
      { eyebrow: "Build real connections", title: "Get verified", text: "Take a short video selfie to show there is a real person behind your profile.", points: ["Only you can complete your verification", "Your result appears as a profile badge"], action: "Continue" },
      { eyebrow: "How it works", title: "How we verify", text: "We compare the face in your video selfie with your profile photos and perform a liveness check.", points: ["Review screenshots are encrypted", "Your video selfie is never public"], action: "Continue" },
      { eyebrow: "Privacy", title: "Verify, not track", text: "We do not keep your video selfie or an underlying facial template after the verification process.", points: ["Verification usually completes within 24 hours", "You can review status in Privacy settings"], action: "Start verification" },
      { eyebrow: "Video selfie", title: "Ready for your close-up?", text: "Frame your face in the oval, find good light, then move slowly toward the camera.", points: [], action: "I’m ready" },
    ],
    ready: "Verification demo is ready",
  },
  fr: {
    label: "Vérification selfie", step: (current) => `${current} / 4`,
    pages: [
      { eyebrow: "Des connexions authentiques", title: "Faites-vous vérifier", text: "Prenez un court selfie vidéo pour confirmer que votre profil est authentique.", points: ["Vous seul pouvez effectuer la vérification", "Le résultat apparaît comme badge"], action: "Continuer" },
      { eyebrow: "Fonctionnement", title: "Comment nous vérifions", text: "Nous comparons le visage de la vidéo aux photos du profil et vérifions qu’il s’agit d’une personne réelle.", points: ["Les captures sont chiffrées", "La vidéo n’est jamais publique"], action: "Continuer" },
      { eyebrow: "Confidentialité", title: "Vérifier, pas suivre", text: "Nous ne conservons ni la vidéo ni un modèle facial après le processus.", points: ["Le résultat arrive généralement sous 24 h", "Le statut reste visible dans Confidentialité"], action: "Commencer" },
      { eyebrow: "Selfie vidéo", title: "Vous êtes prêt·e ?", text: "Placez votre visage dans l’ovale, avec une bonne lumière, puis approchez-vous lentement.", points: [], action: "Je suis prêt·e" },
    ],
    ready: "La démonstration de vérification est prête",
  },
  es: {
    label: "Verificación con selfie", step: (current) => `${current} / 4`,
    pages: [
      { eyebrow: "Conexiones auténticas", title: "Verifica tu perfil", text: "Graba un breve video selfie para demostrar que hay una persona real detrás del perfil.", points: ["Solo tú puedes completar la verificación", "El resultado aparece como una insignia"], action: "Continuar" },
      { eyebrow: "Cómo funciona", title: "Cómo verificamos", text: "Comparamos tu video selfie con las fotos del perfil y hacemos una prueba de vida.", points: ["Las capturas se cifran", "Tu video nunca es público"], action: "Continuar" },
      { eyebrow: "Privacidad", title: "Verificar, no rastrear", text: "No guardamos el video ni una plantilla facial después del proceso.", points: ["Suele completarse en menos de 24 horas", "Puedes revisar el estado en Privacidad"], action: "Empezar" },
      { eyebrow: "Video selfie", title: "¿Todo listo?", text: "Coloca la cara dentro del óvalo, busca buena luz y acércate lentamente.", points: [], action: "Estoy listo" },
    ],
    ready: "La demostración de verificación está lista",
  },
  de: {
    label: "Selfie-Verifizierung", step: (current) => `${current} / 4`,
    pages: [
      { eyebrow: "Echte Verbindungen", title: "Profil verifizieren", text: "Nimm ein kurzes Video-Selfie auf, um dein Profil als echt zu bestätigen.", points: ["Nur du kannst die Verifizierung abschließen", "Das Ergebnis erscheint als Profilabzeichen"], action: "Weiter" },
      { eyebrow: "So funktioniert es", title: "So verifizieren wir", text: "Wir vergleichen das Gesicht im Video mit deinen Profilfotos und führen eine Echtheitsprüfung durch.", points: ["Prüfbilder werden verschlüsselt", "Dein Video ist niemals öffentlich"], action: "Weiter" },
      { eyebrow: "Datenschutz", title: "Prüfen, nicht verfolgen", text: "Nach dem Prozess speichern wir weder das Video noch eine Gesichtsvorlage.", points: ["Die Prüfung dauert meist weniger als 24 Stunden", "Den Status findest du unter Datenschutz"], action: "Verifizierung starten" },
      { eyebrow: "Video-Selfie", title: "Bereit?", text: "Positioniere dein Gesicht im Oval, sorge für gutes Licht und bewege dich langsam näher.", points: [], action: "Ich bin bereit" },
    ],
    ready: "Die Verifizierungsdemo ist bereit",
  },
};

export const chatRoomCopy = {
  "zh-CN": { back: "返回", chat: "聊天", profile: "资料", invite: "约 TA 一起运动", inviteMeta: "跑步 · 周六 08:00 · High Park", greeting: "周六想一起慢跑吗？", reply: "可以！我 8 点前能到。", placeholder: "写一条消息…", send: "发送" },
  en: { back: "Back", chat: "Chat", profile: "Profile", invite: "Make a plan", inviteMeta: "Running · Saturday 08:00 · High Park", greeting: "Would you like to do an easy run on Saturday?", reply: "Yes! I can be there just before 8.", placeholder: "Write a message…", send: "Send" },
  fr: { back: "Retour", chat: "Discussion", profile: "Profil", invite: "Proposer une sortie", inviteMeta: "Course · Samedi 8 h · High Park", greeting: "Partante pour une course tranquille samedi ?", reply: "Oui ! Je peux arriver juste avant 8 h.", placeholder: "Écrire un message…", send: "Envoyer" },
  es: { back: "Volver", chat: "Chat", profile: "Perfil", invite: "Proponer un plan", inviteMeta: "Running · Sábado 08:00 · High Park", greeting: "¿Te apetece un trote suave el sábado?", reply: "¡Sí! Puedo llegar justo antes de las 8.", placeholder: "Escribe un mensaje…", send: "Enviar" },
  de: { back: "Zurück", chat: "Chat", profile: "Profil", invite: "Ein Treffen planen", inviteMeta: "Laufen · Samstag 08:00 · High Park", greeting: "Hast du Samstag Lust auf einen lockeren Lauf?", reply: "Ja! Ich kann kurz vor 8 da sein.", placeholder: "Nachricht schreiben…", send: "Senden" },
};

// Profile editor labels shared by the inline personal-detail controls.
Object.assign(profileCopy["zh-CN"], { detailsHelp: "选择在个人资料上展示的信息", showOnProfile: "在资料上展示", saveChanges: "保存修改" });
Object.assign(profileCopy.en, { detailsHelp: "Choose what appears on your profile.", showOnProfile: "Show on profile", saveChanges: "Save changes" });
Object.assign(profileCopy.fr, { detailsHelp: "Choisissez les informations visibles sur votre profil.", showOnProfile: "Afficher sur le profil", saveChanges: "Enregistrer les modifications" });
Object.assign(profileCopy.es, { detailsHelp: "Elige qué mostrar en tu perfil.", showOnProfile: "Mostrar en el perfil", saveChanges: "Guardar cambios" });
Object.assign(profileCopy.de, { detailsHelp: "Wähle, was auf deinem Profil sichtbar ist.", showOnProfile: "Im Profil anzeigen", saveChanges: "Änderungen speichern" });
