const en = {
  close: 'Close', title: 'Make the\nfirst move.', intro: 'More ways to meet someone who shares your active life.',
  likes: 'See who likes you', likesDesc: 'See full profiles and find out what you have in common.',
  direct: 'Invite before you match', directDesc: 'Suggest an activity you could enjoy together. They choose whether to join.',
  host: 'Make room for new faces', hostDesc: 'Create public activities as a verified host and get to know people in person.',
  freeNote: 'Matching, chatting with matches and joining public activities stay free.',
  inviteReason: 'Inviting someone before you match is a Plus benefit.', hostReason: 'Host your next activity with Plus.',
  loading: 'Loading membership…', error: 'We couldn’t load this right now. Please try again.', retry: 'Try again',
  subscribe: 'Continue with Plus', unavailable: 'Available in the iOS app', iosNote: 'Subscriptions will be available in the PACE iOS app.',
  restore: 'Restore purchases', manage: 'Manage subscription', terms: 'Terms of Use', privacy: 'Privacy Policy',
  renewing: 'Renews automatically. Manage or cancel in your Apple account settings.',
  active: 'Your Plus is active', free: 'PACE Free', expired: 'Your Plus has ended', revoked: 'Your Plus is no longer active',
  grace: 'Review your Apple payment details to keep Plus.', next: 'Renews on', until: 'Access until',
  pending: 'Your purchase is pending Apple approval. We’ll refresh your membership when you return.',
  cancelled: 'Purchase cancelled. Your membership hasn’t changed.', restored: 'Purchases restored.',
  noPurchases: 'No active subscription was found for this account.', verified: 'Your Plus membership is ready.',
  verifyFailed: 'Your purchase hasn’t been confirmed yet. Use Restore purchases to check again.',
  working: 'Please wait…', billing: 'Your membership', refresh: 'Refresh membership', view: 'View Plus', see: 'See likes',
  interest: 'Something in common.', interestTitle: 'Start with a like.\nSee where it goes.', interestDesc: 'See who likes you, find a shared interest, and decide whether to make a move.',
  inviteTitle: 'Make a plan', inviteIntro: 'Send an activity invitation to', recipientNote: 'They can accept or decline. An invitation does not create a match.',
  sport: 'Sport', when: 'Date & time', location: 'Meeting place', locationHint: 'Choose a public meeting spot',
  note: 'A short note (optional)', noteHint: 'An easy run, then coffee?', send: 'Send invitation', sent: 'Invitation sent',
  sentNote: 'Your invitation is pending. They can accept or decline your plan.', done: 'Done',
  invalidTime: 'Choose a future date and time.', duplicate: 'You already have a pending invitation to this person.',
  blocked: 'You can’t invite this person right now.', noLikes: 'A shared interest is a place to start.',
  noLikesDesc: 'When someone likes you, their profile will appear here.', period: {day:'day',week:'week',month:'month',year:'year'},
};
const zh = {
  close:'关闭', title: '从共同热爱，\n到认识彼此。', intro: '从喜欢的运动聊起，多一些认识彼此的机会。',
  likes:'看看谁喜欢你', likesDesc: '查看喜欢你的人的完整资料，找到可以聊起的共同点。',
  direct:'匹配前，先发出邀约', directDesc: '提议一个可以一起享受的活动，由对方决定是否加入。',
  host: '用共同热爱，认识新的人', hostDesc: '完成认证后创建公开活动，在一起运动中认识彼此。',
  freeNote:'匹配、与已匹配的人聊天、参加公开活动，始终免费。',
  inviteReason:'向未匹配的人发出邀约，是 Plus 专属权益。', hostReason:'用 Plus 组织你的下一场活动。',
  loading:'正在加载会员信息…', error:'暂时无法加载，请稍后重试。', retry:'重试',
  subscribe:'继续开通 Plus', unavailable:'在 iOS App 中开通', iosNote:'订阅将于 PACE iOS App 中提供。',
  restore:'恢复购买', manage:'管理订阅', terms:'使用条款', privacy:'隐私政策', renewing:'订阅自动续期，可在 Apple 账户设置中管理或取消。',
  active:'你的 Plus 已生效', free:'PACE 免费版', expired:'你的 Plus 已到期', revoked:'你的 Plus 已失效',
  grace:'请更新 Apple 支付信息以继续使用 Plus。', next:'下次续期', until:'权益有效期至',
  pending:'购买正在等待 Apple 批准。返回 App 后会刷新会员状态。', cancelled:'已取消购买，会员状态未改变。',
  restored:'已恢复购买。', noPurchases:'此账户暂无有效订阅。', verified:'你的 Plus 会员已就绪。',
  verifyFailed:'购买尚未确认，请使用「恢复购买」再次检查。', working:'请稍候…', billing:'我的会员', refresh:'刷新会员状态', view:'了解 Plus', see:'查看喜欢',
  interest: '从共同点开始。', interestTitle: '从一个喜欢，\n开始了解彼此。', interestDesc: '看看谁喜欢你，找一个共同话题，再决定是否主动邀约。',
  inviteTitle: '约个共同喜欢的活动', inviteIntro: '发出活动邀约给', recipientNote:'对方可以接受或拒绝。发出邀约不会自动匹配。',
  sport:'运动项目', when:'日期和时间', location:'集合地点', locationHint:'选择一个公共集合地点',
  note:'附言（可选）', noteHint:'轻松跑完，再喝杯咖啡？', send:'发送邀约', sent:'邀约已发送',
  sentNote: '邀约正在等待回应，对方可以接受或拒绝这个计划。', done:'完成', invalidTime:'请选择未来的日期和时间。',
  duplicate:'你已经向此人发出过待回应的邀约。', blocked:'暂时无法向此人发出邀约。',
  noLikes: '从共同喜欢的事情开始认识。', noLikesDesc:'当有人喜欢你，他们的资料会显示在这里。',
  period:{day:'天',week:'周',month:'个月',year:'年'},
};

const fr = {
  close:'Fermer',title:'Faites le\npremier pas.',intro: 'Plus de façons de rencontrer quelqu’un qui partage votre goût du sport.',
  likes:'Voyez qui vous aime',likesDesc: 'Découvrez les profils complets et trouvez vos points communs.',direct:'Invitez avant le match',directDesc: 'Proposez une activité à partager. La personne choisit si elle vous rejoint.',host: 'Faites place à de nouvelles rencontres',hostDesc: 'Créez des activités publiques en tant qu’hôte vérifié pour faire connaissance en personne.',freeNote:'Les matchs, les discussions entre matchs et la participation aux activités restent gratuits.',inviteReason: 'Inviter avant un match est un avantage Plus.',hostReason:'Organisez votre prochaine activité avec Plus.',
  loading:'Chargement de votre abonnement…',error:'Chargement impossible pour le moment. Réessayez.',retry:'Réessayer',subscribe:'Continuer avec Plus',unavailable:'Disponible dans l’app iOS',iosNote:'Les abonnements seront disponibles dans l’app PACE pour iOS.',restore:'Restaurer les achats',manage:'Gérer l’abonnement',terms:'Conditions d’utilisation',privacy:'Confidentialité',renewing:'Renouvellement automatique. Gérez ou annulez dans les réglages de votre compte Apple.',
  active:'Votre abonnement Plus est actif',free:'PACE Gratuit',expired:'Votre abonnement Plus a expiré',revoked:'Votre abonnement Plus n’est plus actif',grace:'Vérifiez vos informations de paiement Apple pour conserver Plus.',next:'Renouvellement le',until:'Accès jusqu’au',pending:'Votre achat attend l’approbation d’Apple. Votre abonnement sera actualisé à votre retour.',cancelled:'Achat annulé. Votre abonnement n’a pas changé.',restored:'Achats restaurés.',noPurchases:'Aucun abonnement actif trouvé pour ce compte.',verified:'Votre abonnement Plus est prêt.',verifyFailed:'Votre achat n’est pas encore confirmé. Utilisez Restaurer les achats pour vérifier.',working:'Veuillez patienter…',billing:'Votre abonnement',refresh:'Actualiser l’abonnement',view:'Découvrir Plus',see:'Voir les mentions J’aime',
  interest: 'Un point commun.',interestTitle: 'Un J’aime pour commencer.\nÀ vous de voir la suite.',interestDesc: 'Découvrez qui vous aime, trouvez un intérêt commun et décidez si vous faites le premier pas.',inviteTitle:'Proposez un programme',inviteIntro:'Envoyez une invitation sportive à',recipientNote:'La personne peut accepter ou refuser. Une invitation ne crée pas de match.',sport:'Sport',when:'Date et heure',location:'Lieu de rencontre',locationHint:'Choisissez un lieu public',note:'Un petit mot (facultatif)',noteHint:'Une course tranquille, puis un café ?',send:'Envoyer l’invitation',sent:'Invitation envoyée',sentNote: 'Votre invitation attend une réponse. La personne peut accepter ou refuser votre programme.',done:'Terminé',invalidTime:'Choisissez une date et une heure futures.',duplicate:'Une invitation à cette personne est déjà en attente.',blocked:'Vous ne pouvez pas inviter cette personne pour le moment.',noLikes: 'Un intérêt commun pour commencer.',noLikesDesc:'Les profils des personnes qui vous aiment apparaîtront ici.',period:{day:'jour',week:'semaine',month:'mois',year:'an'},
};
const es = {
  close:'Cerrar',title:'Da el\nprimer paso.',intro: 'Más formas de conocer a alguien que comparta tu vida activa.',
  likes:'Mira a quién le gustas',likesDesc: 'Descubre los perfiles completos y lo que tenéis en común.',direct:'Invita antes del match',directDesc: 'Propón una actividad que podáis disfrutar juntos. La otra persona decide si se une.',host: 'Haz sitio para caras nuevas',hostDesc: 'Crea actividades públicas como anfitrión verificado para conoceros en persona.',freeNote:'Los matches, chatear con tus matches y participar en actividades públicas siguen siendo gratuitos.',inviteReason:'Invitar antes del match es una ventaja Plus.',hostReason:'Organiza tu próxima actividad con Plus.',
  loading:'Cargando tu suscripción…',error:'No pudimos cargarlo. Inténtalo de nuevo.',retry:'Reintentar',subscribe:'Continuar con Plus',unavailable:'Disponible en la app iOS',iosNote:'Las suscripciones estarán disponibles en la app PACE para iOS.',restore:'Restaurar compras',manage:'Gestionar suscripción',terms:'Condiciones de uso',privacy:'Privacidad',renewing:'Renovación automática. Gestiona o cancela en los ajustes de tu cuenta Apple.',
  active:'Tu suscripción Plus está activa',free:'PACE Gratis',expired:'Tu suscripción Plus ha vencido',revoked:'Tu suscripción Plus ya no está activa',grace:'Revisa tus datos de pago de Apple para conservar Plus.',next:'Se renueva el',until:'Acceso hasta',pending:'Tu compra espera la aprobación de Apple. Actualizaremos tu suscripción cuando vuelvas.',cancelled:'Compra cancelada. Tu suscripción no ha cambiado.',restored:'Compras restauradas.',noPurchases:'No se encontró una suscripción activa para esta cuenta.',verified:'Tu suscripción Plus está lista.',verifyFailed:'Tu compra aún no está confirmada. Usa Restaurar compras para comprobarla.',working:'Un momento…',billing:'Tu suscripción',refresh:'Actualizar suscripción',view:'Descubrir Plus',see:'Ver a quién le gustas',
  interest: 'Algo en común.',interestTitle: 'Empieza con un like.\nDescubre qué surge.',interestDesc: 'Mira a quién le gustas, encuentra un interés común y decide si das el primer paso.',inviteTitle:'Propón un plan',inviteIntro: 'Envía una invitación a una actividad a',recipientNote:'Puede aceptar o rechazar. Una invitación no crea un match.',sport:'Deporte',when:'Fecha y hora',location:'Punto de encuentro',locationHint:'Elige un punto de encuentro público',note:'Una nota breve (opcional)',noteHint:'¿Una carrera suave y después un café?',send:'Enviar invitación',sent:'Invitación enviada',sentNote: 'Tu invitación está pendiente. La otra persona puede aceptar o rechazar el plan.',done:'Listo',invalidTime:'Elige una fecha y hora futuras.',duplicate:'Ya tienes una invitación pendiente a esta persona.',blocked:'No puedes invitar a esta persona ahora.',noLikes: 'Un interés en común para empezar.',noLikesDesc:'Cuando le gustes a alguien, su perfil aparecerá aquí.',period:{day:'día',week:'semana',month:'mes',year:'año'},
};
const de = {
  close:'Schließen',title:'Mach den\nersten Schritt.',intro: 'Mehr Möglichkeiten, jemanden kennenzulernen, der dein aktives Leben teilt.',
  likes:'Sieh, wer dich mag',likesDesc: 'Sieh dir vollständige Profile an und entdecke eure Gemeinsamkeiten.',direct:'Einladen vor dem Match',directDesc: 'Schlage eine gemeinsame Aktivität vor. Die andere Person entscheidet, ob sie mitmacht.',host: 'Platz für neue Begegnungen',hostDesc: 'Erstelle öffentliche Aktivitäten als verifizierter Gastgeber und lernt euch persönlich kennen.',freeNote:'Matches, Chats mit Matches und die Teilnahme an öffentlichen Aktivitäten bleiben kostenlos.',inviteReason:'Eine Einladung vor dem Match ist ein Plus-Vorteil.',hostReason:'Organisiere deine nächste Aktivität mit Plus.',
  loading:'Mitgliedschaft wird geladen…',error:'Das konnte gerade nicht geladen werden. Versuche es erneut.',retry:'Erneut versuchen',subscribe:'Mit Plus fortfahren',unavailable:'In der iOS-App verfügbar',iosNote:'Abonnements werden in der PACE-App für iOS verfügbar sein.',restore:'Käufe wiederherstellen',manage:'Abo verwalten',terms:'Nutzungsbedingungen',privacy:'Datenschutz',renewing:'Automatische Verlängerung. Verwalte oder kündige das Abo in deinen Apple-Account-Einstellungen.',
  active:'Deine Plus-Mitgliedschaft ist aktiv',free:'PACE Kostenlos',expired:'Deine Plus-Mitgliedschaft ist abgelaufen',revoked:'Deine Plus-Mitgliedschaft ist nicht mehr aktiv',grace:'Prüfe deine Apple-Zahlungsdaten, um Plus weiterzunutzen.',next:'Verlängerung am',until:'Zugang bis',pending:'Dein Kauf wartet auf Apples Freigabe. Wir aktualisieren deine Mitgliedschaft, wenn du zurückkehrst.',cancelled:'Kauf abgebrochen. Deine Mitgliedschaft bleibt unverändert.',restored:'Käufe wiederhergestellt.',noPurchases:'Für dieses Konto wurde kein aktives Abo gefunden.',verified:'Deine Plus-Mitgliedschaft ist bereit.',verifyFailed:'Dein Kauf ist noch nicht bestätigt. Prüfe ihn über Käufe wiederherstellen.',working:'Einen Moment…',billing:'Deine Mitgliedschaft',refresh:'Mitgliedschaft aktualisieren',view:'Plus entdecken',see:'Likes ansehen',
  interest: 'Etwas gemeinsam.',interestTitle: 'Es beginnt mit einem Like.\nSchau, was daraus wird.',interestDesc: 'Sieh, wer dich mag, entdecke gemeinsame Interessen und entscheide, ob du den ersten Schritt machst.',inviteTitle:'Mach einen Plan',inviteIntro: 'Plane eine gemeinsame Aktivität mit',recipientNote:'Die Person kann annehmen oder ablehnen. Eine Einladung erzeugt kein Match.',sport:'Sport',when:'Datum und Uhrzeit',location:'Treffpunkt',locationHint:'Wähle einen öffentlichen Treffpunkt',note:'Kurze Nachricht (optional)',noteHint:'Ein lockerer Lauf, dann Kaffee?',send:'Einladung senden',sent:'Einladung gesendet',sentNote: 'Deine Einladung wartet auf eine Antwort. Die Person kann deinen Plan annehmen oder ablehnen.',done:'Fertig',invalidTime:'Wähle ein Datum und eine Uhrzeit in der Zukunft.',duplicate:'Du hast dieser Person bereits eine offene Einladung geschickt.',blocked:'Du kannst diese Person gerade nicht einladen.',noLikes: 'Ein gemeinsames Interesse ist ein Anfang.',noLikesDesc:'Wenn dich jemand mag, erscheint das Profil hier.',period:{day:'Tag',week:'Woche',month:'Monat',year:'Jahr'},
};
const copy = {en,'zh-CN':zh,fr,es,de};
export function membershipCopy(language) { return copy[language] ?? en; }
